server:
  port: 8080
spring:
  application:
    name: "NameProject"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"
    password: ""
    driverClassName: "org.h2.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"

jwt:
  secret: "xp7k/y5l11sP843RzDze/O6REfDlcoMq4mZWLlVNTaI="
  subject: "nisum"
  accesstokenvalidity: "3600000"

regex:
  password: ^(?=.*[A-Z])(?=.*[0-9])(?=.*[a-zA-Z]).{8,}$
  email: ^[A-Za-z0-9+_.-]+@(.+)$

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"